apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumble-word
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jumble-word
  template:
    metadata:
      labels:
        app: jumble-word
    spec:
      containers:
      - name: jumble-word
        image: belalkhan/jumble-word-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jumble-word-nodeport
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
      name: http
  selector:
    app: jumble-word