apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumble-word
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: jumble-word
  template:
    metadata:
      labels:
        app: jumble-word
    spec:
      containers:
      - name: jumble-word
        image: {{ .Values.deployment.image }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jumble-word-nodeport
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
      name: http
  selector:
    app: jumble-word